-- The -history read index.
--
-- play_history_dedup (guild_id, played_at, webpage_url) only PARTIALLY serves
-- `WHERE guild_id = $1 ORDER BY played_at DESC, id DESC LIMIT $2`: played_at is
-- presorted but id is not, so Postgres plans an Incremental Sort and must
-- consume an entire equal-played_at group before it can emit the first row.
--
-- Equal-played_at groups are not rare and not small. parse_history_entry
-- defaults a missing played_at to 0.0, _sanitize_entry collapses NaN and
-- out-of-range values to 0.0, and backfill_history imports legacy entries that
-- predate the field entirely — so a backfilled guild can carry tens of
-- thousands of rows at to_timestamp(0). Measured on postgres:18 with 1M rows,
-- a guild with 50k epoch-0 rows:
--
--   Limit (actual time=78.580..78.602 rows=50)
--     -> Incremental Sort  Presorted Key: played_at
--        -> Index Scan Backward using play_history_dedup  rows=50000
--                                                   Buffers: shared hit=9964
--
--   p50 49.98ms / max 136.5ms, vs p50 1.34ms for an ordinary guild.
--
-- This index matches the ORDER BY exactly, so the plan becomes a plain backward
-- index scan with no sort node and a bounded buffer count.
--
-- Plain CREATE INDEX, not CONCURRENTLY: db_migrate runs each migration inside a
-- transaction and CONCURRENTLY cannot. It takes a brief write lock on
-- play_history; the only writer is the drainer, which retries.
CREATE INDEX IF NOT EXISTS play_history_recent
    ON play_history (guild_id, played_at DESC, id DESC);
